### ISSUE TITLE
Не работает ссылка на ошибки

### ISSUE THREAD

**Issue by vmugue** [evotor/documentation#6]
В /index.md

**Comment by Lytkini** [comment]
Добрый день. Спасибо за внимательность!
95% ссылок в документации – относительные. Они будут работать только при создании html-файлов из исходников в md.

Пожалуйста, ориентируйтесь на документацию тут: https://developer.evotor.ru/docs/.

На этом сайте представлена вся информация, которая есть в тут в исходниках.

Ещё раз спасибо.
